//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrolment
    {
        public int CourseId { get; set; }
        public int StudentId { get; set; }
        public string Year { get; set; }
        public decimal Semester { get; set; }
        public string Grade { get; set; }
        public Nullable<decimal> Rate { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
